# Generated by Django 4.1.7 on 2023-04-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_apparentrelations_mediaresponse_mediausage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apparentrelations',
            options={'verbose_name_plural': 'Apparent Relationships'},
        ),
        migrations.AlterModelOptions(
            name='mediaresponse',
            options={'verbose_name_plural': 'Media Response'},
        ),
        migrations.AlterModelOptions(
            name='mediausage',
            options={'verbose_name_plural': 'Media Usage'},
        ),
        migrations.AlterModelOptions(
            name='ovawpotherfactors',
            options={'verbose_name_plural': 'Ovawp other factors'},
        ),
    ]
