# Generated by Django 4.1.7 on 2023-04-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_apparentrelations_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intro',
            options={'verbose_name_plural': 'Introduction'},
        ),
    ]
