# Generated by Django 4.1.7 on 2023-03-15 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentageovawp', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=6, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ovawp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatsPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=4, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=12, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('gendercategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.gendercategory')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentageovawp', models.IntegerField(default=0)),
                ('frequency', models.CharField(max_length=40, unique=True)),
                ('usagepercent', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('ovawp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.ovawp')),
                ('socialplatform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.socialplatform')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentageovawp', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('ovawp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.ovawp')),
            ],
        ),
        migrations.AddField(
            model_name='gendercategory',
            name='ovawp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.ovawp'),
        ),
        migrations.AddField(
            model_name='gendercategory',
            name='statsperiod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.statsperiod'),
        ),
        migrations.CreateModel(
            name='CommentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentcategory', models.CharField(max_length=12, unique=True)),
                ('percentage', models.IntegerField(default=0)),
                ('gendercategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.gendercategory')),
            ],
        ),
        migrations.CreateModel(
            name='AgeBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentageovawp', models.IntegerField(default=0)),
                ('agebracket', models.CharField(max_length=128, unique=True)),
                ('ovawp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.ovawp')),
            ],
        ),
    ]
