# Generated by Django 4.1.7 on 2023-03-17 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agegroup', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=6, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Gender categories',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.CreateModel(
            name='StatsPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Stats period',
            },
        ),
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=12)),
                ('slug', models.SlugField()),
                ('gendercategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.gendercategory')),
            ],
            options={
                'unique_together': {('gendercategory', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='PlatformUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=40)),
                ('usagepercent', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
                ('gendercategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.gendercategory')),
                ('socialplatform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.socialplatform')),
            ],
            options={
                'verbose_name_plural': 'Platform Use',
                'unique_together': {('gendercategory', 'socialplatform', 'frequency')},
            },
        ),
        migrations.AddField(
            model_name='gendercategory',
            name='statsperiod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.statsperiod'),
        ),
        migrations.CreateModel(
            name='SocialMediaOvawp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovawp', models.CharField(max_length=128)),
                ('percentage', models.IntegerField(default=0)),
                ('platformuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.platformuse')),
            ],
            options={
                'verbose_name_plural': 'Social Media ovawp',
                'unique_together': {('platformuse', 'ovawp')},
            },
        ),
        migrations.CreateModel(
            name='PartyOvawp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovawp', models.CharField(max_length=128)),
                ('percentage', models.IntegerField(default=0)),
                ('partyname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.party')),
            ],
            options={
                'verbose_name_plural': 'Party ovawp',
                'unique_together': {('partyname', 'ovawp')},
            },
        ),
        migrations.CreateModel(
            name='GenderOvawp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovawp', models.CharField(max_length=128)),
                ('percentage', models.IntegerField(default=0)),
                ('gendercategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.gendercategory')),
            ],
            options={
                'verbose_name_plural': 'Gender ovawp',
                'unique_together': {('gendercategory', 'ovawp')},
            },
        ),
        migrations.CreateModel(
            name='CommentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentcategory', models.CharField(max_length=12)),
                ('percentage', models.IntegerField(default=0)),
                ('gendercategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.gendercategory')),
                ('socialplatform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.socialplatform')),
            ],
            options={
                'verbose_name_plural': 'Comment stats',
                'unique_together': {('gendercategory', 'socialplatform', 'commentcategory')},
            },
        ),
        migrations.CreateModel(
            name='AgeOvawp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovawp', models.CharField(max_length=128)),
                ('percentage', models.IntegerField(default=0)),
                ('agegroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.agebracket')),
            ],
            options={
                'verbose_name_plural': 'Age ovawp',
                'unique_together': {('agegroup', 'ovawp')},
            },
        ),
    ]
