# Generated by Django 4.1.7 on 2023-03-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollicy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsperiod',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
