# Generated by Django 4.1.7 on 2023-03-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollicy_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentStats',
        ),
    ]
