# Generated by Django 4.1.7 on 2023-03-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollicy_app', '0002_alter_statsperiod_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentstats',
            options={'verbose_name_plural': 'Comment stats'},
        ),
        migrations.AlterModelOptions(
            name='gendercategory',
            options={'verbose_name_plural': 'Gender categories'},
        ),
        migrations.AlterModelOptions(
            name='ovawp',
            options={'verbose_name_plural': 'Ovamp'},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name_plural': 'Parties'},
        ),
        migrations.AlterModelOptions(
            name='platformuse',
            options={'verbose_name_plural': 'Platform Use'},
        ),
        migrations.AlterModelOptions(
            name='statsperiod',
            options={'verbose_name_plural': 'Stats period'},
        ),
    ]
