# Generated by Django 4.1.7 on 2023-03-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollicy_app', '0003_alter_commentstats_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agebracket',
            name='ovawp',
        ),
        migrations.RemoveField(
            model_name='agebracket',
            name='percentageovawp',
        ),
        migrations.RemoveField(
            model_name='gendercategory',
            name='ovawp',
        ),
        migrations.RemoveField(
            model_name='gendercategory',
            name='percentageovawp',
        ),
        migrations.RemoveField(
            model_name='party',
            name='ovawp',
        ),
        migrations.RemoveField(
            model_name='party',
            name='percentageovawp',
        ),
        migrations.RemoveField(
            model_name='platformuse',
            name='ovawp',
        ),
        migrations.RemoveField(
            model_name='platformuse',
            name='percentageovawp',
        ),
        migrations.DeleteModel(
            name='Ovawp',
        ),
    ]
