# Generated by Django 4.1.7 on 2023-03-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollicy_app', '0004_remove_agebracket_ovawp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentstats',
            name='commentcategory',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='platformuse',
            name='frequency',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='socialplatform',
            name='platform',
            field=models.CharField(max_length=12),
        ),
    ]
