# Generated by Django 4.1.7 on 2023-03-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollicy_app', '0005_alter_commentstats_commentcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformuse',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='socialplatform',
            name='slug',
            field=models.SlugField(),
        ),
    ]
