# Generated by Django 4.1.7 on 2023-03-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollicy_app', '0006_alter_platformuse_slug_alter_socialplatform_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentstats',
            unique_together={('gendercategory', 'commentcategory')},
        ),
        migrations.AlterUniqueTogether(
            name='platformuse',
            unique_together={('socialplatform', 'frequency')},
        ),
        migrations.AlterUniqueTogether(
            name='socialplatform',
            unique_together={('gendercategory', 'platform')},
        ),
    ]
