# Generated by Django 4.1.7 on 2023-03-15 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollicy_app', '0008_platformuse_gendercategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agebracket',
            old_name='agebracket',
            new_name='agegroup',
        ),
        migrations.AddField(
            model_name='agebracket',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='slug',
            field=models.SlugField(default=' ', unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PartyOvawp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovawp', models.CharField(max_length=128)),
                ('percentage', models.IntegerField(default=0)),
                ('partyname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.party')),
            ],
            options={
                'verbose_name_plural': 'Party ovawp',
                'unique_together': {('partyname', 'ovawp')},
            },
        ),
        migrations.CreateModel(
            name='GenderOvawp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovawp', models.CharField(max_length=128)),
                ('percentage', models.IntegerField(default=0)),
                ('gendercategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.gendercategory')),
            ],
            options={
                'verbose_name_plural': 'Gender ovawp',
                'unique_together': {('gendercategory', 'ovawp')},
            },
        ),
        migrations.CreateModel(
            name='AgeOvawp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovawp', models.CharField(max_length=128)),
                ('percentage', models.IntegerField(default=0)),
                ('agegroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.agebracket')),
            ],
            options={
                'verbose_name_plural': 'Age ovawp',
                'unique_together': {('agegroup', 'ovawp')},
            },
        ),
    ]
