# Generated by Django 4.1.7 on 2023-03-15 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollicy_app', '0009_rename_agebracket_agebracket_agegroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaOvawp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovawp', models.CharField(max_length=128)),
                ('percentage', models.IntegerField(default=0)),
                ('platformuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollicy_app.platformuse')),
            ],
            options={
                'verbose_name_plural': 'Social Media ovawp',
                'unique_together': {('platformuse', 'ovawp')},
            },
        ),
    ]
